name: diff
on: 
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
    
      # kazoeciao のインストール (latest)
      - name: Setup kazoeciao
        run: |
          Invoke-WebRequest -Uri "https://ftp.vector.co.jp/71/79/3284/kazoeciao.zip" -Outfile ".\kazoeciao.zip"
          Expand-Archive -Path .\kazoeciao.zip -DestinationPath .\kazoeciao
          ls
          cd .\kazoeciao
          mkdir .\tmp
          .\kazoeciao.exe /a../setting/sample.cas
          cd tmp
          cat .\*.csv




